"""FMCSA property-carrying HOS limits (assessment scope)."""

MAX_DRIVING_HOURS = 11.0
MAX_WINDOW_HOURS = 14.0
BREAK_AFTER_DRIVING_HOURS = 8.0
BREAK_DURATION_MINUTES = 30
MIN_OFF_DUTY_HOURS = 10.0
MAX_CYCLE_ON_DUTY_HOURS = 70.0
CYCLE_ROLLING_DAYS = 8

PICKUP_DURATION_HOURS = 1.0
DROPOFF_DURATION_HOURS = 1.0
FUEL_INTERVAL_MILES = 1000.0
FUEL_STOP_HOURS = 0.5  # 30 minutes on duty

# Average fallback if routing duration missing (mph)
DEFAULT_AVG_SPEED_MPH = 55.0

RESTART_34_HOURS = 34.0
